# Generated by Django 5.1.7 on 2025-03-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='answers',
            field=models.JSONField(blank=True),
        ),
    ]
